# Generated by Django 6.1 on 2026-08-08 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kamera')),
                ('camera_id', models.CharField(max_length=50, unique=True, verbose_name='ID Kamera')),
                ('source', models.CharField(default='0', max_length=200, verbose_name='Sumber Kamera (0 untuk webcam, URL untuk IP Camera)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('auto_analysis', models.BooleanField(default=True, verbose_name='Analisis Otomatis')),
                ('analysis_interval', models.IntegerField(default=5, verbose_name='Interval Analisis (detik)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Konfigurasi Kamera',
                'verbose_name_plural': 'Konfigurasi Kamera',
            },
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Deteksi')),
                ('image', models.ImageField(upload_to='detections/%Y/%m/%d/', verbose_name='Gambar')),
                ('detection_type', models.CharField(choices=[('realtime', 'Kamera Real-time'), ('upload', 'Upload Manual')], max_length=20, verbose_name='Tipe Deteksi')),
                ('detected_class', models.CharField(max_length=50, verbose_name='Kelas Terdeteksi')),
                ('confidence', models.FloatField(verbose_name='Confidence Score')),
                ('bbox_coords', models.TextField(verbose_name='Koordinat Bounding Box')),
                ('behavior_detected', models.CharField(blank=True, max_length=100, verbose_name='Perilaku Terdeteksi')),
                ('behavior_confidence', models.FloatField(blank=True, null=True, verbose_name='Confidence Perilaku')),
                ('disease_name_id', models.CharField(max_length=100, verbose_name='Nama Penyakit (ID)')),
                ('disease_name_en', models.CharField(max_length=100, verbose_name='Nama Penyakit (EN)')),
                ('causes', models.TextField(verbose_name='Penyebab')),
                ('symptoms', models.TextField(blank=True, verbose_name='Gejala')),
                ('treatment', models.TextField(blank=True, verbose_name='Penanganan')),
                ('prevention', models.TextField(blank=True, verbose_name='Pencegahan')),
                ('severity_level', models.CharField(blank=True, max_length=20, verbose_name='Tingkat Keparahan')),
                ('immediate_action', models.TextField(blank=True, verbose_name='Tindakan Segera')),
                ('is_anomaly', models.BooleanField(default=False, verbose_name='Anomali')),
                ('alert_sent', models.BooleanField(default=False, verbose_name='Alert Terkirim')),
            ],
            options={
                'verbose_name': 'Hasil Deteksi',
                'verbose_name_plural': 'Hasil Deteksi',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alert_type', models.CharField(choices=[('disease_detected', 'Penyakit Terdeteksi'), ('anomaly_behavior', 'Perilaku Anomali'), ('system_error', 'Error Sistem')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='detection.detectionresult')),
            ],
            options={
                'verbose_name': 'Log Alert',
                'verbose_name_plural': 'Log Alert',
                'ordering': ['-timestamp'],
            },
        ),
    ]
